// sigmashake-abyss — regression test
// Regression — the public script surface is pinned against drift.
// Generated by shared/agent-config/scripts/generate-kind-tests.ts — runtime-free:
// asserts invariants from the project's own files (deterministic, PSU-safe).

import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, test } from "vitest";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..");

function readJson(p: string) {
  const raw = readFileSync(p, "utf8");
  return JSON.parse(raw);
}
function pkg() {
  return readJson(join(ROOT, "package.json"));
}

describe("sigmashake-abyss regression — public script surface is stable", () => {
  test("retains a test script", () => {
    const sc = pkg().scripts || {};
    expect(Object.keys(sc).some((k) => k === "test" || k.startsWith("test:"))).toBe(true);
  });
  test("package name keeps its expected shape", () => {
    const n = pkg().name || "";
    expect(/^(@[\w-]+\/[\w.-]+|[\w.-]+)$/.test(n)).toBe(true);
  });
  test("public mirror and SAST scripts stay discoverable", () => {
    const sc = pkg().scripts || {};
    expect(sc["test:sast"]).toBe("vitest run test/sast/");
    expect(sc["mirror:public"]).toBe("bash scripts/publish-abyss-mirror.sh");
    expect(sc["mirror:public:evidence"]).toBe(
      "bash scripts/publish-abyss-mirror.sh --write-evidence /tmp/abyss-mirror-evidence.env",
    );
  });
});

describe("sigmashake-abyss regression — public mirror contract", () => {
  const scriptPath = join(ROOT, "scripts/publish-abyss-mirror.sh");
  const privateServiceBinding = "sigmashake-" + "alerts";

  test("mirror script exists and is allowlist-only", () => {
    expect(existsSync(scriptPath)).toBe(true);
    const script = readFileSync(scriptPath, "utf8");
    expect(script).toContain("Allowlist-only public copy");
    expect(script).toContain('"src"');
    expect(script).toContain('"public"');
    expect(script).toContain('"integrations"');
    expect(script).toContain('"test"');
    expect(script).toContain('"SPEC_SHEET.md"');
  });

  test("mirror uses example Wrangler config and not production config", () => {
    const script = readFileSync(scriptPath, "utf8");
    expect(script).toContain('"wrangler.example.toml"');
    expect(script).not.toMatch(/copy_tree "wrangler\.toml"/);

    const example = readFileSync(join(ROOT, "wrangler.example.toml"), "utf8");
    expect(example).toContain("<YOUR_R2_ARCHIVE_BUCKET>");
    expect(example).not.toContain(privateServiceBinding);
  });

  test("mirror requires fail-closed scanning", () => {
    const script = readFileSync(scriptPath, "utf8");
    expect(script).toContain("gitleaks is required");
    expect(script).toContain("MMO_HMAC_KEY");
    expect(script).toContain("sigmashake-''alerts");
  });

  test("public collaboration docs exist", () => {
    for (const rel of [
      "AGENTS.md",
      "SPEC_SHEET.md",
      "integrations/README.md",
      "integrations/contracts/README.md",
    ]) {
      expect(existsSync(join(ROOT, rel)), rel).toBe(true);
    }
  });
});
