// sigmashake-abyss — dr test
// Disaster recovery — the service is reconstitutable from committed artifacts.
// Generated by shared/agent-config/scripts/generate-kind-tests.ts — runtime-free:
// asserts invariants from the project's own files (deterministic, PSU-safe).

import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, test } from "vitest";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..");

function readJson(p: string) {
  const raw = readFileSync(p, "utf8");
  return JSON.parse(raw);
}
function pkg() {
  return readJson(join(ROOT, "package.json"));
}
function wranglerText(): { name: string; text: string } | null {
  for (const n of ["wrangler.toml", "wrangler.jsonc", "wrangler.json"]) {
    const p = join(ROOT, n);
    if (existsSync(p)) return { name: n, text: readFileSync(p, "utf8") };
  }
  return null;
}

describe("sigmashake-abyss dr — reconstitutable from committed artifacts", () => {
  test("a deploy/build descriptor is committed", () => {
    expect(existsSync(join(ROOT, "package.json"))).toBe(true);
  });
  test("the service declares how to rebuild or redeploy itself", () => {
    const p = pkg();
    const sc = p.scripts || {};
    const w = wranglerText();
    const reproducible =
      !!w ||
      !!p.bin ||
      !!p.main ||
      !!(sc.build || sc.deploy || sc.start || sc.compile || sc.package || sc.dev);
    expect(reproducible).toBe(true);
  });
});
