// SIGMA ABYSS — the bestiary.
//
// Archetype defs carry MULTIPLIERS against a level/depth baseline, not
// absolute numbers — so one curve scales the whole roster. makeEnemy()
// stamps out a concrete combatant; combat.js and progression.js never
// touch the raw defs.
//
// `special` hooks (resolved in combat.js):
//   steal — a landed hit yanks a random inventory item (the Tarkov fear)
//   hex   — a landed hit stacks an attack-down debuff for the encounter
//   curse — a landed hit rolls a nasty per-encounter curse
//
// `lpc` is the paperdoll build spec for the LPC sprite renderer — inert data
// the sim never reads. cosmetics.enemyBuild() translates it into render layers.
// Shape: { body:'human'|'skeleton'|'zombie', skin?, hair?, hairColor?, shirt?,
//          pants?, hat?(asset id), wings?(asset id), scale? }. `hue` is kept
// only as the boot-time fallback tint before LPC assets finish loading.

export const ENEMIES = {
  // ── trash ───────────────────────────────────────────────────────────
  goblin: {
    name: "Goblin",
    kind: "normal",
    special: null,
    hue: 110,
    tag: "runt",
    hp: 0.45,
    atk: 0.7,
    def: 0.5,
    spd: 1.0,
    xp: 1.0,
    lootBonus: 0,
    lpc: {
      body: "human",
      skin: "green",
      hair: "spiky",
      hairColor: "dark_brown",
      pants: "brown",
      weapon: true,
      scale: 0.78,
    },
  },
  goblin_thief: {
    name: "Loot Thief",
    kind: "normal",
    special: "steal",
    hue: 78,
    tag: "thief",
    hp: 0.4,
    atk: 0.55,
    def: 0.6,
    spd: 1.35,
    xp: 1.25,
    lootBonus: 0,
    lpc: {
      body: "human",
      skin: "green",
      hair: "short",
      hairColor: "black",
      shirt: "charcoal",
      pants: "charcoal",
      scale: 0.8,
    },
  },
  skeleton: {
    name: "Skeleton",
    kind: "normal",
    special: null,
    hue: 46,
    tag: "bones",
    hp: 0.55,
    atk: 0.8,
    def: 0.4,
    spd: 0.9,
    xp: 1.0,
    lootBonus: 0,
    lpc: { body: "skeleton", scale: 0.92 },
  },
  rogue_wizard: {
    name: "Rogue Wizard",
    kind: "normal",
    special: "hex",
    hue: 280,
    tag: "hexer",
    hp: 0.5,
    atk: 1.05,
    def: 0.35,
    spd: 0.95,
    xp: 1.35,
    lootBonus: 0,
    lpc: {
      body: "human",
      skin: "light",
      hair: "long",
      hairColor: "gray",
      shirt: "purple",
      pants: "purple",
      hat: "hat_wizard",
      scale: 0.95,
    },
  },
  imp: {
    name: "Imp",
    kind: "normal",
    special: null,
    hue: 6,
    tag: "imp",
    hp: 0.4,
    atk: 0.9,
    def: 0.45,
    spd: 1.2,
    xp: 1.15,
    lootBonus: 0,
    lpc: {
      body: "human",
      skin: "black",
      hair: "spiky",
      hairColor: "red",
      pants: "maroon",
      wings: "wings_bat",
      scale: 0.68,
    },
  },
  cursed_biker: {
    name: "Cursed Biker",
    kind: "normal",
    special: null,
    hue: 26,
    tag: "rider",
    hp: 0.7,
    atk: 1.0,
    def: 0.6,
    spd: 1.25,
    xp: 1.45,
    lootBonus: 0,
    lpc: {
      body: "human",
      skin: "taupe",
      hair: "spiky",
      hairColor: "black",
      shirt: "black",
      pants: "charcoal",
      scale: 0.95,
    },
  },
  corrupted_knight: {
    name: "Corrupted Knight",
    kind: "normal",
    special: null,
    hue: 210,
    tag: "knight",
    hp: 0.95,
    atk: 1.05,
    def: 0.95,
    spd: 0.8,
    xp: 1.65,
    lootBonus: 1,
    lpc: {
      body: "human",
      skin: "bronze",
      hair: "short",
      hairColor: "dark_gray",
      shirt: "slate",
      pants: "slate",
      hat: "hat_bowler",
      weapon: { material: "cloth", ramp: "charcoal" },
      scale: 1.0,
    },
  },
  abyss_crawler: {
    name: "Abyss Crawler",
    kind: "normal",
    special: "hex",
    hue: 188,
    tag: "crawler",
    hp: 0.8,
    atk: 1.25,
    def: 0.7,
    spd: 1.1,
    xp: 1.8,
    lootBonus: 1,
    lpc: { body: "zombie", scale: 0.9 },
  },
  // Fantasy-canon roster — the overlay surfaces these by tag-emoji so
  // viewers immediately recognize the foe even before LPC sprites paint.
  wolf: {
    name: "Dire Wolf",
    kind: "normal",
    special: null,
    hue: 30,
    tag: "wolf",
    hp: 0.42,
    atk: 0.85,
    def: 0.4,
    spd: 1.4,
    xp: 1.1,
    lootBonus: 0,
    lpc: {
      body: "human",
      skin: "taupe",
      hair: "long",
      hairColor: "dark_gray",
      shirt: "brown",
      pants: "brown",
      scale: 0.85,
    },
  },
  boar: {
    name: "Tusked Boar",
    kind: "normal",
    special: null,
    hue: 18,
    tag: "boar",
    hp: 0.8,
    atk: 0.9,
    def: 0.85,
    spd: 0.95,
    xp: 1.3,
    lootBonus: 0,
    lpc: {
      body: "human",
      skin: "taupe",
      hair: "short",
      hairColor: "dark_brown",
      pants: "charcoal",
      scale: 0.95,
    },
  },
  bandit: {
    name: "Bandit",
    kind: "normal",
    special: "steal",
    hue: 12,
    tag: "bandit",
    hp: 0.55,
    atk: 0.95,
    def: 0.55,
    spd: 1.15,
    xp: 1.3,
    lootBonus: 0,
    lpc: {
      body: "human",
      skin: "light",
      hair: "short",
      hairColor: "black",
      shirt: "maroon",
      pants: "charcoal",
      hat: "hat_beanie",
      scale: 0.95,
    },
  },
  troll: {
    name: "Cave Troll",
    kind: "normal",
    special: null,
    hue: 88,
    tag: "troll",
    hp: 1.6,
    atk: 1.05,
    def: 0.95,
    spd: 0.6,
    xp: 1.9,
    lootBonus: 1,
    lpc: {
      body: "human",
      skin: "pale_green",
      hair: "long",
      hairColor: "green",
      pants: "brown",
      scale: 1.25,
    },
  },

  // ── elites — bigger, scarier, drop better ───────────────────────────
  cursed_gambler: {
    name: "Cursed Trickster",
    kind: "elite",
    special: "curse",
    hue: 48,
    tag: "trickster",
    hp: 1.5,
    atk: 1.2,
    def: 0.9,
    spd: 1.1,
    xp: 3.4,
    lootBonus: 2,
    lpc: {
      body: "human",
      skin: "light",
      hair: "short",
      hairColor: "black",
      shirt: "maroon",
      pants: "charcoal",
      hat: "hat_tophat",
      scale: 1.05,
    },
  },
  bone_colossus: {
    name: "Bone Colossus",
    kind: "elite",
    special: null,
    hue: 40,
    tag: "colossus",
    hp: 3.1,
    atk: 1.45,
    def: 1.7,
    spd: 0.6,
    xp: 4.2,
    lootBonus: 2,
    lpc: { body: "skeleton", scale: 1.55 },
  },
  infernal_champion: {
    name: "Infernal Champion",
    kind: "elite",
    special: null,
    hue: 351,
    tag: "champion",
    hp: 2.4,
    atk: 1.85,
    def: 1.35,
    spd: 1.0,
    xp: 4.8,
    lootBonus: 3,
    lpc: {
      body: "human",
      skin: "black",
      hair: "spiky",
      hairColor: "red",
      shirt: "red",
      pants: "maroon",
      wings: "wings_bat",
      scale: 1.3,
    },
  },
  abyss_hunter: {
    name: "Abyss Hunter",
    kind: "elite",
    special: "steal",
    hue: 262,
    tag: "hunter",
    hp: 2.0,
    atk: 2.15,
    def: 1.05,
    spd: 1.55,
    xp: 5.4,
    lootBonus: 3,
    lpc: {
      body: "human",
      skin: "olive",
      hair: "long",
      hairColor: "raven",
      shirt: "forest",
      pants: "charcoal",
      hat: "hat_cap",
      scale: 1.2,
    },
  },
  ogre: {
    name: "Ogre Brute",
    kind: "elite",
    special: null,
    hue: 50,
    tag: "ogre",
    hp: 2.8,
    atk: 2.0,
    def: 1.4,
    spd: 0.55,
    xp: 4.4,
    lootBonus: 2,
    lpc: {
      body: "human",
      skin: "olive",
      hair: "short",
      hairColor: "black",
      shirt: "maroon",
      pants: "brown",
      hat: "hat_helmbarbarian",
      scale: 1.5,
    },
  },
  werewolf: {
    name: "Werewolf",
    kind: "elite",
    special: null,
    hue: 40,
    tag: "werewolf",
    hp: 1.9,
    atk: 2.3,
    def: 0.95,
    spd: 1.7,
    xp: 5.0,
    lootBonus: 3,
    lpc: {
      body: "human",
      skin: "taupe",
      hair: "spiky",
      hairColor: "dark_gray",
      shirt: "charcoal",
      pants: "charcoal",
      scale: 1.3,
    },
  },

  // ── bosses — run-enders, guaranteed strong loot ─────────────────────
  goblin_king: {
    name: "The Goblin King",
    kind: "boss",
    special: null,
    hue: 122,
    tag: "king",
    hp: 5.6,
    atk: 1.6,
    def: 1.4,
    spd: 1.0,
    xp: 9,
    lootBonus: 4,
    lpc: {
      body: "human",
      skin: "green",
      hair: "spiky",
      hairColor: "dark_brown",
      shirt: "maroon",
      pants: "brown",
      hat: "hat_crown",
      weapon: { material: "hair", ramp: "gold" },
      scale: 1.4,
    },
  },
  hollow_druid: {
    name: "The Hollow Druid",
    kind: "boss",
    special: "hex",
    hue: 95,
    tag: "druid",
    hp: 7.6,
    atk: 2.0,
    def: 1.5,
    spd: 1.0,
    xp: 14,
    lootBonus: 5,
    lpc: {
      body: "human",
      skin: "pale_green",
      hair: "long",
      hairColor: "green",
      shirt: "forest",
      pants: "forest",
      hat: "hat_wizard",
      scale: 1.5,
    },
  },
  chrome_centurion: {
    name: "Chrome Centurion",
    kind: "boss",
    special: null,
    hue: 196,
    tag: "centurion",
    hp: 10,
    atk: 2.5,
    def: 2.2,
    spd: 1.1,
    xp: 21,
    lootBonus: 5,
    lpc: {
      body: "human",
      skin: "taupe",
      hair: "short",
      hairColor: "dark_gray",
      shirt: "slate",
      pants: "slate",
      hat: "hat_bowler",
      scale: 1.7,
    },
  },
  catacomb_tyrant: {
    name: "The Catacomb Tyrant",
    kind: "boss",
    special: "curse",
    hue: 340,
    tag: "tyrant",
    hp: 14,
    atk: 3.0,
    def: 2.4,
    spd: 1.0,
    xp: 31,
    lootBonus: 6,
    lpc: { body: "zombie", shirt: "purple", pants: "charcoal", hat: "hat_crown", scale: 1.8 },
  },
  hollow_sigma: {
    name: "The Hollow Sigma",
    kind: "boss",
    special: "steal",
    hue: 272,
    tag: "sigma",
    hp: 20,
    atk: 3.6,
    def: 2.8,
    spd: 1.2,
    xp: 46,
    lootBonus: 6,
    lpc: {
      body: "human",
      skin: "black",
      hair: "spiky",
      hairColor: "raven",
      shirt: "black",
      pants: "black",
      wings: "wings_bat",
      hat: "hat_crown",
      weapon: { material: "hair", ramp: "gold" },
      scale: 2.0,
    },
  },
};

export const ENEMY_IDS = Object.keys(ENEMIES);

// The level/depth baseline a "1.0 mult" enemy is measured against.
function baselineAt(level, depth) {
  return {
    hp: 26 + level * 7 + depth * 4,
    atk: 5 + level * 1.2 + depth * 0.6,
    def: 3 + level * 0.8 + depth * 0.4,
  };
}

// Stamp out a concrete combatant scaled to a level + delve depth. `rng`
// is optional — when present it adds a little stat variance so two
// goblins are never identical.
export function makeEnemy(id, level, depth, rng) {
  const def = ENEMIES[id] || ENEMIES.goblin;
  const base = baselineAt(Math.max(1, level), Math.max(0, depth));
  const v = rng ? rng.float(0.9, 1.12) : 1;
  const maxHp = Math.max(1, Math.round(base.hp * def.hp * v));
  return {
    id,
    name: def.name,
    kind: def.kind,
    special: def.special,
    hue: def.hue,
    tag: def.tag,
    lpc: def.lpc,
    maxHp,
    hp: maxHp,
    attack: Math.max(1, base.atk * def.atk * v),
    defense: Math.max(0, base.def * def.def),
    speed: def.spd,
    xp: def.xp,
    lootBonus: def.lootBonus,
    // per-encounter mutable state (combat.js writes these)
    hexStacks: 0,
    threat: def.kind === "boss" ? 3 : def.kind === "elite" ? 2 : 1,
  };
}

export function enemyDef(id) {
  return ENEMIES[id] || null;
}
