// sigmashake-abyss — e2e test
// End-to-end — the config->entrypoint->surface chain is wired through.
// Generated by shared/agent-config/scripts/generate-kind-tests.ts — runtime-free:
// asserts invariants from the project's own files (deterministic, PSU-safe).

import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, test } from "vitest";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..");

function readJson(p: string) {
  const raw = readFileSync(p, "utf8");
  return JSON.parse(raw);
}
function pkg() {
  return readJson(join(ROOT, "package.json"));
}
function wranglerText(): { name: string; text: string } | null {
  for (const n of ["wrangler.toml", "wrangler.jsonc", "wrangler.json"]) {
    const p = join(ROOT, n);
    if (existsSync(p)) return { name: n, text: readFileSync(p, "utf8") };
  }
  return null;
}
function readdirSafe(d: string): string[] {
  try {
    return readdirSync(d);
  } catch {
    return [];
  }
}
function collectSrc(): string[] {
  const out: string[] = [];
  const walk = (dir: string): void => {
    for (const e of readdirSafe(dir)) {
      if (e === "node_modules" || e === "dist" || e === "public" || e.startsWith(".")) continue;
      const full = join(dir, e);
      let isDir = false;
      try {
        isDir = statSync(full).isDirectory();
      } catch {
        continue;
      }
      if (isDir) walk(full);
      else if (/\.(ts|tsx|js|mjs|cjs)$/.test(full) && !/\.(test|spec)\./.test(full)) out.push(full);
    }
  };
  for (const r of ["src", "lib", "tools", "scripts", "overlay", "worker"]) walk(join(ROOT, r));
  if (out.length === 0) {
    for (const e of readdirSafe(ROOT)) {
      if (/\.(ts|js|mjs|cjs)$/.test(e) && !/\.(test|spec|config)\./.test(e))
        out.push(join(ROOT, e));
    }
  }
  return out;
}

describe("sigmashake-abyss e2e — entrypoint chain is wired end to end", () => {
  test("an executable surface exists (worker main, bin, src entry, or run script)", () => {
    const p = pkg();
    const w = wranglerText();
    const hasWorkerMain = !!(w && /main\s*[:=]/.test(w.text));
    const hasBin = !!p.bin;
    const hasSrc = collectSrc().length > 0;
    const sc = p.scripts || {};
    const hasStart = !!(sc.start || sc.dev || sc.serve || sc.deploy);
    expect(hasWorkerMain || hasBin || hasSrc || hasStart).toBe(true);
  });
});
